const $=id=>document.getElementById(id);
const clamp=x=>Math.max(0,Math.min(1,x));
const ease=x=>1-(1-clamp(x))**3;
const wave=()=>'<div class="wave">'+Array.from({length:54},()=>'<i></i>').join('')+'</div>';
const tool=(text,delay)=>`<div class="tool" data-reveal="${delay}"><span class="check">✓</span>${text}<small>已完成</small></div>`;
const file=(name,type)=>`<div class="file"><span class="check">↗</span>${name}<small>${type}</small></div>`;
const scenes=[
 {at:0,end:5,k:'MEET YOUR AI WORKSPACE',title:'让想法<br><em>开始执行</em>',value:'从一句目标，到一整套成果。',tags:['miniQ','桌面 AI 协作助手'],feature:'从想法到交付',benefit:'表达目标 → 执行任务 → 交付成果',html:()=>`<img class="heroart" src="assets/launch.png"><div class="row between" style="margin-top:22px"><span class="heading" style="margin:0">你的 AI 工作搭档</span><span class="pill">图片 · 音乐 · 文档</span></div>`},
 {at:5,end:13,k:'01 / VOICE TO ACTION',title:'语音输入<br><em>开口就开工</em>',value:'说出目标，立即开始。',tags:['语音输入','实时转写'],feature:'语音输入',benefit:'少打字，更快进入工作状态',html:()=>`<div class="eyebrow">VOICE INPUT</div><div class="heading">说出你想完成的事</div>${wave()}<div class="row between"><span class="status" id="voice-status">● 正在聆听 · 动效演示</span><span class="muted">中文 · 自动识别</span></div><div class="input"><span id="transcript"></span><span style="color:#8b9fff">▏</span></div><div class="row between" style="margin-top:25px"><span class="muted">工作区：产品发布</span><span class="btn" id="send">发送目标 ↑</span></div>`},
 {at:13,end:21,k:'02 / TOOLS IN MOTION',title:'工具执行<br><em>每步都可见</em>',value:'重复操作，交给 AI。',tags:['文件读写','搜索','浏览器'],feature:'任务执行时间线',benefit:'把重复操作交给 AI，把注意力留给判断',html:()=>`<div class="bubble">整理产品资料，准备发布报告和创意素材。</div>${tool('读取 README.md · 了解产品',.3)}${tool('搜索项目资料 · 汇总功能',1.3)}${tool('运行命令 · 检查工作区',2.3)}<div class="card" data-reveal="3.4"><div class="row between"><b style="font-size:24px">浏览器操作</b><span class="pill">动效演示</span></div><p class="muted" style="margin-top:14px">打开项目看板 → 定位内容 → 填写发布摘要</p><div class="row between" style="margin-top:17px"><span style="font-size:20px">发布准备 · 资料已整理</span><span class="btn">预览摘要 ↗</span></div></div>`},
 {at:21,end:29,k:'03 / IMAGE GENERATION',title:'生成图像<br><em>创意立刻成形</em>',value:'描述创意，得到画面。',tags:['原生生图','结果可预览'],feature:'生成图片',benefit:'从文字创意，走到可见的画面',html:()=>`<div class="bubble" style="font-size:21px;padding:13px 20px">生成深蓝、蓝紫霓虹的未来科技主视觉。</div><img class="image" src="assets/launch.png" data-reveal=".6"><div class="row between" style="margin-top:15px"><span style="font-size:24px">launch.png</span><span class="status" style="margin:0">✓ 实际 AI 生图结果</span></div><p class="muted" style="margin-top:9px">1672 × 941 · PNG · 已保存至制作工作区</p>`},
 {at:29,end:36,k:'04 / MUSIC CREATION',title:'生成配乐<br><em>让灵感有节奏</em>',value:'一句话，配好节奏。',tags:['电子律动','纯音乐','音频产物'],feature:'生成配乐',benefit:'图片和声音，在一个工作流里完成',html:()=>`<div class="bubble">为科技产品创作年轻、动感的电子纯音乐。</div><div class="card"><div class="row"><span class="btn" style="font-size:30px">Ⅱ</span><div><div class="heading" style="margin:0">Neon Motion</div><p class="muted">电子 · 活力 · 无人声</p></div></div>${wave()}<div style="height:5px;background:#283657;border-radius:5px"><div id="music-progress" style="height:100%;background:#8e8bff"></div></div><div class="row between" style="margin-top:15px"><span class="muted" id="music-time">00:00</span><span class="muted">音频播放动效演示</span></div></div><div style="margin-top:22px">${file('科技主题配乐.wav','WAV')}</div>`},
 {at:36,end:44,k:'05 / READY TO DELIVER',title:'文档交付<br><em>拿到就能用</em>',value:'成果成文件，打开就能用。',tags:['DOCX','XLSX','PNG','WAV'],feature:'产物与文档预览',benefit:'结果落在文件里，协作走到交付',html:()=>`<div class="paper"><div class="eyebrow" style="color:#45669a">PRODUCT LAUNCH / 工作成果</div><h2 style="margin-top:12px">miniQ 产品发布报告</h2><p>产品能力、创意素材与执行计划，汇总为一份可交付文档。</p><table><tr><td>内容</td><td>产物</td><td>状态</td></tr><tr><td>产品功能与价值</td><td>产品报告.docx</td><td>已整理</td></tr><tr><td>发布安排与分工</td><td>发布计划.xlsx</td><td>已整理</td></tr><tr><td>科技视觉与主题配乐</td><td>PNG / WAV</td><td>已准备</td></tr></table></div><div class="files" data-reveal="1">${file('产品报告.docx','DOCX')}${file('发布计划.xlsx','XLSX')}${file('科技主视觉.png','PNG')}${file('主题配乐.wav','WAV')}</div>`},
 {at:44,end:52,k:'06 / STAY IN CONTROL',title:'操作审批<br><em>关键一步你定</em>',value:'关键操作，由你决定。',tags:['请求批准','替我审批','完全访问'],feature:'操作审批',benefit:'自动化向前推进，决定权始终在你',html:()=>`<div class="row"><span class="check">!</span><span class="heading" style="margin:0">需要你的批准</span></div><div class="card" style="border-color:#8274cf"><div class="row between"><span style="font-size:24px">运行命令</span><span class="pill" id="approval-state">等待批准</span></div><p class="muted" style="margin-top:15px">将当前提交推送到远程仓库。</p><div class="code" style="margin-top:20px">git push origin main</div><div class="row" style="margin-top:24px"><span class="btn" id="approve">允许一次</span><span class="btn secondary">本会话允许</span><span class="muted">拒绝</span></div></div><p class="status" id="approval-result">请确认目标和影响后批准</p><p class="muted" style="margin-top:22px">根据审批模式与具体操作，控制执行权限。</p>`},
 {at:52,end:60,k:'07 / MOBILE COMMAND · DESKTOP ACTION',title:'手机远控<br><em>桌面执行</em>',value:'人在外，照样调动电脑。',tags:['手机控制端','电脑执行端','同一工作区'],feature:'手机远控桌面任务',benefit:'手机发送目标 → 桌面执行 → 结果回到手机',html:()=>`<div class="remote-demo"><div class="remote-meta"><span>桌面在线 · 同一工作区</span><span class="pill">远控流程示例 · 非实录</span></div><div class="remote-devices"><div class="phone remote-phone"><div class="notch"></div><div class="remote-role">手机 · 控制端</div><p class="muted">远程已开启 · 已连接</p><div class="remote-request">整理当前工作区资料，生成发布报告</div><div class="remote-send" id="remote-send">发送目标 ↑</div><div class="remote-reply" id="remote-reply"><span class="check">✓</span><b>发布报告.docx</b><p>桌面结果已同步到手机</p></div><div class="remote-hint">需要时，可在手机远程审批</div></div><div class="remote-links"><div class="remote-link-label">发送指令</div><div class="remote-line"><i id="command-dot"></i><span>→</span></div><div class="remote-link-label remote-back-label">返回结果</div><div class="remote-line remote-back"><i id="result-dot"></i><span>←</span></div></div><div class="remote-desktop"><div class="remote-monitor"><div class="remote-role">电脑 · 执行端</div><p class="muted">桌面工作区 / 产品发布</p><div id="remote-desktop-state" class="remote-desktop-state">等待手机指令</div><div class="remote-task" id="remote-read"><span class="check">✓</span><div><b>读取桌面项目资料</b><p>README.md · 发布计划.xlsx</p></div></div><div class="remote-task" id="remote-write"><span class="check">✓</span><div><b>生成发布报告</b><p>整理资料，写入工作区</p></div></div><div class="remote-output" id="remote-output">▤ 发布报告.docx <span>已生成</span></div></div><div class="remote-stand"></div><div class="remote-base"></div><p class="remote-execution-note">任务在电脑执行 · 手机查看结果</p></div></div></div>`},
 {at:60,end:68,k:'08 / REUSE WHAT WORKS',title:'技能复用<br><em>一次变多次</em>',value:'好流程，下次直接用。',tags:['工作区技能','/ 引用技能'],feature:'技能库',benefit:'好方法，不必每次重新解释',html:()=>`<div class="row" style="align-items:stretch"><div class="card" style="flex:1;margin:0"><div class="eyebrow">REUSABLE SKILL</div><div class="heading">周报生成</div><p class="muted">总结本周产出，整理待办，\n生成下一周计划。</p><div class="status">✦ 已保存为工作区技能</div></div><div class="code" style="flex:1">1. 查看最近改动<br>2. 汇总完成事项<br>3. 整理风险与待办<br>4. 输出周报文档</div></div><div class="card" data-reveal="1.5"><div class="eyebrow">输入 / 引用技能</div><div class="heading" style="color:#bac1ff">/weekly-report</div><div class="row between"><span class="muted">周报生成 · 当前工作区</span><span class="btn" id="skill-run">使用技能 ↗</span></div></div><div class="status" id="skill-result">选择技能，复用完整工作流程。</div>`},
 {at:68,end:76,k:'09 / RIGHT ON TIME',title:'定时任务<br><em>到点自己跑</em>',value:'安排一次，到点执行。',tags:['每日简报','每周回顾','项目监控'],feature:'已安排',benefit:'重复事项有节奏地完成',html:()=>`<div class="row between"><span class="heading" style="margin:0">你的自动工作日程</span><span class="btn">＋ 新建任务</span></div>${tool('每日简报',.3)}<p class="muted" style="margin:10px 0 20px 69px">每天 09:00 · 汇总进展与重点</p>${tool('每周回顾',1)}<p class="muted" style="margin:10px 0 20px 69px">每周五 17:00 · 生成周报文档</p>${tool('项目监控',1.7)}<p class="muted" style="margin:10px 0 20px 69px">每 1 小时 · 发现异常及时汇报</p><div class="card" data-reveal="3.5" style="margin-top:12px"><div class="row"><span class="check">✓</span><span style="font-size:22px">每日简报已运行 · 结果已写回会话</span></div></div>`},
 {at:76,end:84,k:'10 / YOUR MODEL, YOUR CHOICE',title:'多模型接入<br><em>适合才好用</em>',value:'按任务，选合适模型。',tags:['国内外模型','自定义接入'],feature:'模型选择',benefit:'选你需要的模型，保持熟悉的工作方式',html:()=>`<div class="eyebrow">MODEL SELECTOR</div><div class="heading">一个工作区，多种模型选择</div><div class="modelgrid">${['GPT','Claude','Gemini','Qwen','DeepSeek','豆包'].map((x,i)=>`<div class="model" data-model="${i}">${x}</div>`).join('')}</div><div class="card"><div class="row"><span class="check">⇄</span><div><b style="font-size:24px">读取 · 搜索 · 执行 · 交付</b><p class="muted" style="margin-top:10px">切换模型，沿用同一工作流</p></div></div></div><p class="muted" style="margin-top:20px">模型可用性与能力取决于接入服务及配置。</p>`},
 {at:84,end:90,k:'MAKE THINGS HAPPEN',title:'miniQ<br><em>下一步，交给它</em>',value:'你说目标，它来执行。',tags:['语音 → 行动','创意 → 成果'],feature:'从目标，到完成',benefit:'miniQ · 你的桌面 AI 协作助手',html:()=>`<div class="eyebrow">ONE WORKSPACE / MANY POSSIBILITIES</div><div class="heading" style="font-size:40px">从灵感开始，把事情做完。</div><div class="featuregrid">${['语音转写 · 工具执行','图片生成 · 对话配乐','文档交付 · 操作审批','手机远控 · 技能复用','定时任务 · 多模型'].map(x=>`<div class="featuretile">${x}</div>`).join('')}</div><div class="row" style="margin-top:37px"><img src="assets/icon.png" style="width:70px;height:70px;border-radius:16px"><span class="large">miniQ</span><span class="muted" style="margin-left:auto">DESKTOP AI</span></div>`}
];
let last=-1;
const real=document.createElement('div');real.id='real';real.innerHTML='<span class="real-tag">真实操作录屏 · 示例素材</span><img id="real-a"><img id="real-b">';$('panel').appendChild(real);
const realFrame=(kind,u)=>`assets/live/${kind}/${String(Math.max(1,Math.min(kind==='settings'?56:69,Math.floor(u*4)+1))).padStart(3,'0')}.jpg`;
function showReal(ix,u){real.style.display='none';real.className='';if(ix===2&&u>4){real.style.display='block';real.querySelector('#real-a').src=realFrame('desktop',u-4)}if(ix===5&&u>4){real.style.display='block';real.querySelector('#real-a').src=realFrame('desktop',u-4)}if(ix===6){real.style.display='block';real.querySelector('#real-a').src=realFrame('desktop',u);if(u>4){real.querySelector('#real-a').src=realFrame('mobile',u-4)}}if(ix===10&&u>4){real.style.display='block';real.querySelector('#real-a').src=realFrame('settings',u-4)}}
$('particles').innerHTML=Array.from({length:35},(_,i)=>`<i style="left:${(i*397)%1920}px;top:${(i*229)%1080}px;opacity:${.15+(i%5)*.09}"></i>`).join('');
window.seek=t=>{
 t=Math.max(0,Math.min(89.999,t)); const ix=scenes.findIndex(s=>t>=s.at&&t<s.end);const s=scenes[ix],u=t-s.at;
 if(ix!==last){$('chapter').textContent=s.k;$('title').innerHTML=s.title;$('value').innerHTML=s.value.replaceAll('\n','<br>');$('tags').innerHTML=s.tags.map(v=>`<span class="tag">${v}</span>`).join('');$('feature').textContent=s.feature;$('benefit').textContent=s.benefit;$('content').innerHTML=s.html();last=ix;}
 document.querySelectorAll('.heroart').forEach(el=>el.style.transform='scale('+ (1.015+.01*Math.sin(u*.5))+')'); const enter=ease(u/.55);$('copy').style.transform=`translateY(${(1-enter)*28}px)`;$('copy').style.opacity=enter;
 $('panel').style.transform=`translate(${(1-enter)*65}px,${Math.sin(u*.7)*2}px) scale(${.985+.015*enter})`;$('panel').style.opacity=.15+.85*enter;
 $('sequence').textContent=`${String(ix+1).padStart(2,'0')} / 12   —   ${s.feature}`;$('time').textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')} / 01:30`;
 $('progress').style.width=`${t/90*100}%`;$('aurora').style.transform=`translate(${Math.sin(t*.17)*100}px,${Math.cos(t*.12)*65}px)`;$('particles').style.transform=`translateY(${-t*1.5}px)`;
 $('grid').style.backgroundPosition=`${t*1.5}px ${t*1.5}px`;$('transition').style.opacity=(1-clamp(u/.4))*.8;showReal(ix,u);
 document.querySelectorAll('[data-reveal]').forEach(el=>{const v=ease((u-Number(el.dataset.reveal))/.5);el.style.opacity=v;el.style.transform=`translateY(${(1-v)*17}px)`;});
 document.querySelectorAll('.wave i').forEach((el,i)=>el.style.height=`${12+72*Math.abs(Math.sin(i*.64+t*5.7))*Math.abs(Math.cos(i*.19-t*2))}px`);
 if(ix===1){const text='根据产品资料写一份发布报告，并生成科技主视觉和主题配乐。';$('transcript').textContent=text.slice(0,Math.floor(clamp((u-.5)/4.5)*text.length));$('voice-status').textContent=u>5.5?'✓ 转写完成 · 目标已就绪':'● 正在聆听 · 动效演示';$('send').style.boxShadow=u>6?'0 0 28px #7783ff80':'none';}
 if(ix===4){$('music-progress').style.width=`${u/7*100}%`;$('music-time').textContent=`00:0${Math.floor(u)}`;}
 if(ix===6){$('approval-state').textContent=u>5?'已批准':'等待批准';$('approval-result').textContent=u>5?'✓ 已允许本次操作 · 继续执行':'请确认目标和影响后批准';$('approve').style.boxShadow=u>4.6&&u<5.4?'0 0 35px #77b5ff':'none';}
 if(ix===7){
  $('remote-send').textContent=u>=1.4?'✓ 目标已发送':'发送目标 ↑';
  $('remote-desktop-state').textContent=u<1.9?'等待手机指令':u<5.2?'● 已接收 · 桌面执行中':'✓ 执行完成 · 返回结果';
  for(const [id,start] of [['remote-read',2.1],['remote-write',3.7],['remote-output',5.0],['remote-reply',6.0]]){$(id).style.opacity=.18+.82*ease((u-start)/.45);}
  $('command-dot').style.left=clamp((u-1.4)/.7)*100+'%';$('command-dot').style.opacity=u>=1.4&&u<2.3?1:0;
  $('result-dot').style.left=(1-clamp((u-5.3)/.7))*100+'%';$('result-dot').style.opacity=u>=5.3&&u<6.2?1:0;
 }
 if(ix===8){$('skill-result').textContent=u>4.3?'✓ 技能已引用 · 正在生成本周周报':'选择技能，复用完整工作流程。';$('skill-run').style.boxShadow=u>3.8&&u<4.7?'0 0 25px #8c8aff':'none';}
 if(ix===10){document.querySelectorAll('[data-model]').forEach((el,i)=>el.classList.toggle('active',i===Math.min(5,Math.floor(u/1.15))));}
};
(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(im=>im.decode().catch(()=>{})));window.seek(0);window.__ready=true;if(location.search.includes('preview')){const start=performance.now();function loop(n){seek((n-start)/1000%90);requestAnimationFrame(loop)}requestAnimationFrame(loop)}})();
