pub fn native_aliases(canonical: &str) -> &'static [&'static str] {
    match canonical {
        "shell_run" => &["Bash", "bash", "shell", "shell_command", "exec_command"],
        "shell_batch" => &["shell_call", "local_shell_call"],
        "file_read" => &["Read", "read", "read_file"],
        "file_write" => &["Write", "write", "write_file"],
        "file_edit" => &["Edit", "edit", "edit_file"],
        "file_patch" => &["MultiEdit", "multi_edit"],
        "apply_patch" => &["ApplyPatch"],
        "notebook_edit" => &["NotebookEdit"],
        "file_glob" => &["Glob", "glob", "glob_files"],
        "file_grep" => &["Grep", "grep", "grep_files"],
        "web_fetch" => &["WebFetch", "fetch_url"],
        "web_search" => &["WebSearch", "search_web"],
        "tool_search" => &["ToolSearch"],
        "ask_user" => &["AskUserQuestion", "ask_user_question", "request_user_input"],
        "task_update" => &["TodoWrite", "update_plan"],
        "task_create" => &["TaskCreate"],
        "task_get" => &["TaskGet"],
        "task_list" => &["TaskList"],
        "task_item_update" => &["TaskUpdate"],
        "agent_run" => &["Task", "Agent"],
        "agent_message" => &["SendMessage"],
        "plan_mode" => &["EnterPlanMode", "ExitPlanMode"],
        "skill_read" => &["Skill"],
        "mcp_call" => &["mcp__<server>__<tool>"],
        "process_output" => &["TaskOutput"],
        "process_kill" => &["KillShell", "TaskStop"],
        _ => &[],
    }
}

pub(super) fn type_glob(kind: &str) -> Option<&'static str> {
    match kind {
        "rust" => Some("*.rs"),
        "py" | "python" => Some("*.py"),
        "js" | "javascript" => Some("*.js"),
        "ts" | "typescript" => Some("*.ts"),
        "tsx" => Some("*.tsx"),
        "jsx" => Some("*.jsx"),
        "go" => Some("*.go"),
        "java" => Some("*.java"),
        "c" => Some("*.c"),
        "cpp" => Some("*.{cc,cpp,cxx,h,hpp}"),
        "cs" => Some("*.cs"),
        "ruby" => Some("*.rb"),
        "php" => Some("*.php"),
        "swift" => Some("*.swift"),
        "kotlin" => Some("*.{kt,kts}"),
        "sh" | "shell" => Some("*.{sh,bash,zsh}"),
        "yaml" => Some("*.{yaml,yml}"),
        "json" => Some("*.json"),
        "toml" => Some("*.toml"),
        "md" | "markdown" => Some("*.{md,mdx}"),
        _ => None,
    }
}
